services:

  mongodb:
    image: mongo
    container_name: mongodb
    ports:
      - "27018:27017"

  api:
    build: .
    container_name: product-api

    ports:
      - "8080:8080"

    depends_on:
      - mongodb

    environment:
      MongoDbSettings__ConnectionString: mongodb://mongodb:27017
      MongoDbSettings__DatabaseName: ProductDb
      MongoDbSettings__CollectionName: Products
      ASPNETCORE_ENVIRONMENT: Docker